modLoader="scorge"
loaderVersion="[3.1,)"
issueTrackerURL="https://github.com/MrTJP/ProjectRed"

[[mods]]
    modId="projectred-core"
    displayName="ProjectRed Core"
    entryClass="mrtjp.projectred.ProjectRedCore"
    version="${version}"

    updateJSONURL="https://version-check.covers1624.net/check/?mod=ProjectRed&mc=${mc_version}"
    displayURL="https://github.com/MrTJP/ProjectRed"
    authors="MrTJP, Chicken Bones, covers1624"
    description='''
Redstone. The way it was meant to be.
    '''
[[dependencies.projectred-core]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.projectred-core]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
[[dependencies.projectred-core]]
    modId="codechickenlib"
    mandatory=true
    versionRange="[${ccl_version},)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.projectred-core]]
    modId="mrtjpcore"
    mandatory=true
    versionRange="[${tjcore_version},)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.projectred-core]]
    modId="cb_multipart"
    mandatory=true
    versionRange="[${cbmp_version},)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.projectred-core]]
    modId="cb_microblock"
    mandatory=true
    versionRange="[${cbmp_version},)"
    ordering="AFTER"
    side="BOTH"

[[mods]]
    modId="projectred-exploration"
    displayName="ProjectRed Exploration"
    entryClass="mrtjp.projectred.ProjectRedExploration"
    version="${version}"

    updateJSONURL="https://version-check.covers1624.net/check/?mod=ProjectRed&mc=${mc_version}"
    displayURL="https://github.com/MrTJP/ProjectRed"
    authors="MrTJP, Chicken Bones, covers1624"
    description='''
Redstone. The way it was meant to be.
    '''
[[dependencies.projectred-exploration]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.projectred-exploration]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
[[dependencies.projectred-exploration]]
    modId="codechickenlib"
    mandatory=true
    versionRange="[${ccl_version},)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.projectred-exploration]]
    modId="mrtjpcore"
    mandatory=true
    versionRange="[${tjcore_version},)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.projectred-exploration]]
    modId="cb_multipart"
    mandatory=true
    versionRange="[${cbmp_version},)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.projectred-exploration]]
    modId="projectred-core"
    mandatory=true
    versionRange="[${version},)"
    ordering="AFTER"
    side="BOTH"

[[mods]]
    modId="projectred-transmission"
    displayName="ProjectRed Transmission"
    entryClass="mrtjp.projectred.ProjectRedTransmission"
    version="${version}"

    updateJSONURL="https://version-check.covers1624.net/check/?mod=ProjectRed&mc=${mc_version}"
    displayURL="https://github.com/MrTJP/ProjectRed"
    authors="MrTJP, Chicken Bones, covers1624"
    description='''
Redstone. The way it was meant to be.
    '''
[[dependencies.projectred-transmission]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.projectred-transmission]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
[[dependencies.projectred-transmission]]
    modId="codechickenlib"
    mandatory=true
    versionRange="[${ccl_version},)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.projectred-transmission]]
    modId="mrtjpcore"
    mandatory=true
    versionRange="[${tjcore_version},)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.projectred-transmission]]
    modId="cb_multipart"
    mandatory=true
    versionRange="[${cbmp_version},)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.projectred-transmission]]
    modId="projectred-core"
    mandatory=true
    versionRange="[${version},)"
    ordering="AFTER"
    side="BOTH"



[[mods]]
    modId="projectred-integration"
    displayName="ProjectRed Integration"
    entryClass="mrtjp.projectred.ProjectRedIntegration"
    version="${version}"

    updateJSONURL="https://version-check.covers1624.net/check/?mod=ProjectRed&mc=${mc_version}"
    displayURL="https://github.com/MrTJP/ProjectRed"
    authors="MrTJP, Chicken Bones, covers1624"
    description='''
Redstone. The way it was meant to be.
    '''
[[dependencies.projectred-integration]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.projectred-integration]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
[[dependencies.projectred-integration]]
    modId="codechickenlib"
    mandatory=true
    versionRange="[${ccl_version},)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.projectred-integration]]
    modId="mrtjpcore"
    mandatory=true
    versionRange="[${tjcore_version},)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.projectred-integration]]
    modId="cb_multipart"
    mandatory=true
    versionRange="[${cbmp_version},)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.projectred-integration]]
    modId="projectred-core"
    mandatory=true
    versionRange="[${version},)"
    ordering="AFTER"
    side="BOTH"

[[mods]]
    modId="projectred-illumination"
    displayName="ProjectRed Illumination"
    entryClass="mrtjp.projectred.ProjectRedIllumination"
    version="${version}"

    updateJSONURL="https://version-check.covers1624.net/check/?mod=ProjectRed&mc=${mc_version}"
    displayURL="https://github.com/MrTJP/ProjectRed"
    authors="MrTJP, Chicken Bones, covers1624"
    description='''
Redstone. The way it was meant to be.
    '''
[[dependencies.projectred-illumination]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.projectred-illumination]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
[[dependencies.projectred-illumination]]
    modId="codechickenlib"
    mandatory=true
    versionRange="[${ccl_version},)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.projectred-illumination]]
    modId="mrtjpcore"
    mandatory=true
    versionRange="[${tjcore_version},)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.projectred-illumination]]
    modId="cb_multipart"
    mandatory=true
    versionRange="[${cbmp_version},)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.projectred-illumination]]
    modId="projectred-core"
    mandatory=true
    versionRange="[${version},)"
    ordering="AFTER"
    side="BOTH"



    [[mods]]
        modId="projectred-expansion"
        displayName="ProjectRed Expansion"
        entryClass="mrtjp.projectred.ProjectRedExpansion"
        version="${version}"

        updateJSONURL="https://version-check.covers1624.net/check/?mod=ProjectRed&mc=${mc_version}"
        displayURL="https://github.com/MrTJP/ProjectRed"
        authors="MrTJP, Chicken Bones, covers1624"
        description='''
    Redstone. The way it was meant to be.
        '''
    [[dependencies.projectred-expansion]]
        modId="forge"
        mandatory=true
        versionRange="[28,)"
        ordering="NONE"
        side="BOTH"
    [[dependencies.projectred-expansion]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.15.2]"
        ordering="NONE"
        side="BOTH"
    [[dependencies.projectred-expansion]]
        modId="codechickenlib"
        mandatory=true
        versionRange="[${ccl_version},)"
        ordering="AFTER"
        side="BOTH"
    [[dependencies.projectred-expansion]]
        modId="mrtjpcore"
        mandatory=true
        versionRange="[${tjcore_version},)"
        ordering="AFTER"
        side="BOTH"
    [[dependencies.projectred-expansion]]
        modId="cb_multipart"
        mandatory=true
        versionRange="[${cbmp_version},)"
        ordering="AFTER"
        side="BOTH"
    [[dependencies.projectred-expansion]]
        modId="projectred-core"
        mandatory=true
        versionRange="[${version},)"
        ordering="AFTER"
        side="BOTH"