/**
 * Used only for generating run configs that include all ProjectRed modules in the classpath.
 */
plugins {
    id 'net.neoforged.moddev'
}

neoForge {
    version = forge_version

    accessTransformers.from "../core/src/main/resources/META-INF/accesstransformer.cfg"

    runs {
        configureEach {
        }

        client {
        }

        server {
        }
    }
}

dependencies {
    runtimeOnly project(":core")
    runtimeOnly project(":expansion")
    runtimeOnly project(":exploration")
    runtimeOnly project(":fabrication")
    runtimeOnly project(":illumination")
    runtimeOnly project(":integration")
    runtimeOnly project(":transmission")
}

