modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/MrTJP/ProjectRed"
license="MIT"

[[mods]]
    modId="projectred_illumination"
    displayName="ProjectRed Illumination"
    version="${file.jarVersion}"

    updateJSONURL="https://version-check.covers1624.net/check/?mod=ProjectRed&mc=${mc_version}"
    displayURL="https://github.com/MrTJP/ProjectRed"
    authors="MrTJP, Chicken Bones, covers1624"
    description='''
Redstone. The way it was meant to be.
    '''
[[dependencies.projectred_illumination]]
    modId="neoforge"
    type="required"
    versionRange="[${forge_version},)"
    ordering="NONE"
    side="BOTH"
[[dependencies.projectred_illumination]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="NONE"
    side="BOTH"
[[dependencies.projectred_illumination]]
    modId="codechickenlib"
    type="required"
    versionRange="[${ccl_version},)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.projectred_illumination]]
    modId="cb_multipart"
    type="required"
    versionRange="[${cbm_version},)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.projectred_illumination]]
    modId="cb_microblock"
    type="required"
    versionRange="[${cbm_version},)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.projectred_illumination]]
    modId="projectred_core"
    type="required"
    versionRange="[${file.jarVersion},)"
    ordering="AFTER"
    side="BOTH"
