modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/MrTJP/ProjectRed"
license="MIT"

[[mods]]
    modId="projectred_core"
    displayName="ProjectRed Core"
    version="${file.jarVersion}"

    updateJSONURL="https://version-check.covers1624.net/check/?mod=ProjectRed&mc=${mc_version}"
    displayURL="https://github.com/MrTJP/ProjectRed"
    authors="MrTJP, Chicken Bones, covers1624"
    description='''
Redstone. The way it was meant to be.
    '''

[[accessTransformers]]
    file="META-INF/accesstransformer.cfg"

[[dependencies.projectred_core]]
    modId="neoforge"
    type="required"
    versionRange="[${forge_version},)"
    ordering="NONE"
    side="BOTH"
[[dependencies.projectred_core]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.4]"
    ordering="NONE"
    side="BOTH"
[[dependencies.projectred_core]]
    modId="codechickenlib"
type="required"
    versionRange="[${ccl_version},)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.projectred_core]]
    modId="cb_multipart"
    type="required"
    versionRange="[${cbm_version},)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.projectred_core]]
    modId="computercraft"
    type="optional"
    versionRange="[${cct_version},)"
    ordering="AFTER"
    side="BOTH"
