modLoader="javafml"
loaderVersion="[${lang_version},)"
issueTrackerURL="https://github.com/MrTJP/ProjectRed"
license="MIT"

[[mods]]
    modId="projectred_core"
    displayName="ProjectRed Core"
    version="${file.jarVersion}"

    updateJSONURL="https://version-check.covers1624.net/check/?mod=ProjectRed&mc=${mc_version}"
    displayURL="https://github.com/MrTJP/ProjectRed"
    authors="MrTJP, Chicken Bones, covers1624"
    description='''
Redstone. The way it was meant to be.
    '''
[[dependencies.projectred_core]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)"
    ordering="NONE"
    side="BOTH"
[[dependencies.projectred_core]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"
[[dependencies.projectred_core]]
    modId="codechickenlib"
    mandatory=true
    versionRange="[${ccl_version},)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.projectred_core]]
    modId="cb_multipart"
    mandatory=true
    versionRange="[${cbm_version},)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.projectred_core]]
    modId="computercraft"
    mandatory=false
    versionRange="[${cct_version},)"
    ordering="AFTER"
    side="BOTH"
