plugins {
    id 'net.neoforged.moddev'
}

String mod_id = 'projectred_expansion'

neoForge {
    version = forge_version

    accessTransformers.from "../core/src/main/resources/META-INF/accesstransformer.cfg"

    runs {
        data {
            data()
            programArguments.addAll '--mod', mod_id, '--all', '--output', file("src/main/generated").absolutePath, '--existing', file("src/main/resources").absolutePath
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }

    unitTest {
        enable()
        testedMod = mods.getByName(mod_id)
    }
}

dependencies {
    implementation "io.codechicken:CodeChickenLib:${mc_version}-${ccl_version}"
    implementation "io.codechicken:CBMultipart:${mc_version}-${cbm_version}"

    accessTransformers "io.codechicken:CodeChickenLib:${mc_version}-${ccl_version}"
    accessTransformers "io.codechicken:CBMultipart:${mc_version}-${cbm_version}"

    compileOnly project(":api")
    implementation project(":core")

    compileOnly "maven.modrinth:embeddium:${embeddium_version}"
    compileOnly "maven.modrinth:sodium:${sodium_version}"

    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.2'
    testRuntimeOnly    'org.junit.jupiter:junit-jupiter-engine:5.8.2'
    testImplementation 'org.mockito:mockito-core:5.14.2'
    testImplementation 'org.mockito:mockito-junit-jupiter:5.14.2'
}

test {
    useJUnitPlatform()
    jvmArgs('-Xmx3G', '-Xms1G')
}
