plugins {
    id 'net.neoforged.moddev'
}

String mod_id = 'projectred_transmission'

neoForge {
    version = forge_version

    accessTransformers.from "../core/src/main/resources/META-INF/accesstransformer.cfg"

    runs {
        data {
            data()
            programArguments.addAll '--mod', mod_id, '--all', '--output', file("src/main/generated").absolutePath, '--existing', file("src/main/resources").absolutePath
        }
    }
}

dependencies {
    implementation "io.codechicken:CodeChickenLib:${mc_version}-${ccl_version}"
    implementation "io.codechicken:CBMultipart:${mc_version}-${cbm_version}"

    accessTransformers "io.codechicken:CodeChickenLib:${mc_version}-${ccl_version}"
    accessTransformers "io.codechicken:CBMultipart:${mc_version}-${cbm_version}"

    compileOnly project(":api")
    implementation project(":core")
}
