name: Cut Release

on:
  workflow_dispatch:
    inputs:
      channel:
        description: 'Release channel'
        required: true
        type: string
      type:
        description: 'Release type'
        required: true
        default: 'beta'
        type: string

jobs:
  push-to-publish-branch:
    name: Push to Publish Branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Update publish branch
        run: |    
          DEST_BRANCH="publish/$CHANNEL/$TYPE"
          echo "Pushing commit from $GITHUB_SHA to $DEST_BRANCH"
          
          # Force push to publish branch
          git push origin $DEST_BRANCH --force

        env:
          CHANNEL: ${{ inputs.channel }}
          TYPE: ${{ inputs.type }}