name: Verify pull requests

on:
  pull_request:
    branches:
      - main
      - main-*

jobs:
  style_check:
    name: Style/Format check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout git repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Commit Linter
      uses: wagoid/commitlint-github-action@v2.0.3

  build_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Extract commit info
        id: commit_info
        run: |
          short_sha="$(git rev-parse --short $GITHUB_SHA)"
          branch_name="pr$(echo $GITHUB_REF | sed -e 's/refs\/pull\/\(.*\)\/merge/\1/')"
          echo "::set-output name=short_sha::$short_sha"
          echo "::set-output name=branch_name::$branch_name"

      - name: Generate version
        id: versioning
        uses: paulhatch/semantic-version@v4.0.1
        with:
          major_pattern: "/^((fix)|(feat)|(perf))(\\([a-z]+\\))?!:/"
          minor_pattern: "/^((fix)|(feat)|(perf))(\\([a-z]+\\))?:/"
          format: "${major}.${minor}.${patch}-${{ steps.commit_info.outputs.branch_name }}.${increment}"

      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/*.properties', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: ./gradlew build # TODO test
        env:
          AUTO_GENERATED_VERSION: ${{ steps.versioning.outputs.version }}

      - name: Cleanup Gradle Cache
        # These files shouldn't be cached according to https://docs.github.com/en/actions/guides/building-and-testing-java-with-gradle
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: project-red-${{ steps.versioning.outputs.version }}
          path: build/libs
